package section23;

import java.math.BigDecimal;

/**
 * The main purpose of record class is to remove the dependency from Lombok
 * libraries.
 */
public record Product(String name, BigDecimal cost, String type) {
	// By default constructors generated by compiler are called canonical
	// constructors.

	// Adding validations
	public Product {
		// name cannot be blank
		if (name != null && name.isBlank()) {
			throw new IllegalArgumentException("name is not valid!");
		}
		// cost cannot be less than or equal to zero
		if (cost.compareTo(BigDecimal.ZERO) <= 0) {
			throw new IllegalArgumentException("cost is not valid!");
		}
	}

	// custom constructor
	public Product(String name, BigDecimal cost) {
		// canonical constructor must be called like below while calling custom
		// constructor
		this(name, cost, "General");
	}
}
